# Generated by Django 3.2.10 on 2022-02-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_projects", "0003_alter_projectmodel_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmodel",
            name="variables",
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="variables",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="app_projects.variablemodel",
            ),
        ),
    ]
