# Generated by Django 3.2.10 on 2022-02-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_projects", "0006_alter_projectmodel_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmodel",
            name="variables",
        ),
        migrations.AddField(
            model_name="variablemodel",
            name="project",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variable",
                to="app_projects.projectmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="variablemodel",
            unique_together={("name", "project")},
        ),
    ]
