# Generated by Django 3.2.10 on 2022-02-21 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_projects", "0007_auto_20220221_1459"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmodel",
            options={
                "permissions": (
                    ("can_view", "Может просматривать"),
                    ("can_edit", "Может редактировать"),
                    ("can_add", "Может добавлять"),
                    ("can_delete", "Может удалять"),
                )
            },
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="shared",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="project_shared",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="project_viewers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
